#!/usr/bin/with-contenv bash

# we have to set it, otherwise chrome won't find ~/.asoundrc file
HOME=/home/jibri
# content of launch.sh --> exec java -Djava.util.logging.config.file=/etc/jitsi/jibri/logging.properties -Dconfig.file="/etc/jitsi/jibri/jibri.conf" -jar /opt/jitsi/jibri/jibri.jar --config "/etc/jitsi/jibri/config.json"
DAEMON=/opt/jitsi/jibri/launch.sh
#DAEMON="exec java -Djava.util.logging.config.file=/etc/jitsi/jibri/logging.properties -Dconfig.file=/etc/jitsi/jibri/jibri.conf -jar /opt/jitsi/jibri/jibri.jar"
exec s6-setuidgid jibri /bin/bash -c "exec $DAEMON"