version: '3.8'

services:
    jibri:
        image: prayagsingh/jibri-pulseaudio:latest
        restart: "on-failure"
        volumes:
            - ./config:/config:Z
            - /dev/shm:/dev/shm
        cap_add:
            - SYS_ADMIN
            - NET_BIND_SERVICE
        extra_hosts:
            - "meet.example.com:1.2.3.4" # update_this
        environment:
            # rclone config
            ENABLE_RCLONE: 0 # false by default
            S3_REMOTE_NAME: ""
            S3_PROVIDER_NAME: ""
            RCLONE_ENV_AUTH: ""
            AWS_ACCESS_KEY_ID: "" 
            AWS_SECRET_ACCESS_KEY: ""
            S3_REGION: ""
            S3_ENDPOINT: ""
            # jibri config
            XMPP_SERVER: "xmpp.meet.example.com"
            XMPP_DOMAIN: "meet.example.com"
            XMPP_AUTH_DOMAIN: "auth.meet.example.com"
            XMPP_BOSH_URL_BASE: "http://xmpp.meet.example.com:5280"
            XMPP_GUEST_DOMAIN: "guest.meet.example.com"
            XMPP_MUC_DOMAIN: "muc.meet.example.com"
            XMPP_INTERNAL_MUC_DOMAIN: "internal-muc.meet.example.com"
            XMPP_RECORDER_DOMAIN: "recorder.meet.example.com"
            TZ: "Asia/Kolkata"
            JIBRI_BREWERY_MUC: "jibribrewery"
            JIBRI_PENDING_TIMEOUT: "90"
            JIBRI_XMPP_USER: "jibri"
            JIBRI_XMPP_PASSWORD: "password"
            JIBRI_RECORDER_USER: "recorder"
            JIBRI_RECORDER_PASSWORD: "password"
            DISPLAY: ":0"
            JIBRI_RECORDING_DIR: "/config/jibri/recording"
            JIBRI_FINALIZE_RECORDING_SCRIPT_PATH: "/config/jibri/finalize.sh"
            JIBRI_STRIP_DOMAIN_JID: "muc"
            JIBRI_LOGS_DIR: "/config/jibri/logs"
            # new config
            ENABLE_JIBRI_HTTP_API_PORT: 1
            JIBRI_HTTP_API_EXTERNAL_PORT: 2222
            JIBRI_HTTP_API_INTERNAL_PORT: 3333
            JIBRI_USAGE_TIMEOUT: 0
            XMPP_TRUST_ALL_CERTS: "true"
            CHROMIUM_FLAGS: "--use-fake-ui-for-media-stream,--start-maximized,--kiosk,--enabled,--disable-infobars,--autoplay-policy=no-user-gesture-required"
            ENABLE_STATS_D: "true"
            JIBRI_FFMPEG_RESOLUTION: "1280x720"
            JIBRI_FFMPEG_AUDIO_SOURCE: "pulse"
            JIBRI_FFMPEG_AUDIO_DEVICE: "default"
            PUBLIC_URL: ""
            XORG_DUMMY_VIDEO_RESOLUTION: "1280 720"
        networks:
            jitsi:
networks:
    jitsi:
      external: true
